version: 1
jobs:
  compile:
    image: node
    script:
      - git add package-lock.json
      - git commit -m "package-lock"
      - git push
      - npm install truffle
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npx truffle test
stages:
  - pipeline:
      jobs:
        - compile
        - test